apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website
bases:
- ../workload
images:
- name: devlaunchers/platform-website
  newName: devlaunchers/platform-website
  newTag: 2f25b77-202107110510 # {"$imagepolicy": "platform-website:platform-website:tag"}
